services:
  # FastAPI 애플리케이션
  podpod-api-dev:
    build:
      context: ../services/api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # 환경 설정 파일 지정
      CONFIG_FILE: /app/config/config.dev.yaml

      PROFILE: DEV

      # 데이터베이스 연결
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      # 보안 관련 (Infisical에서 주입된 환경 변수 전달)
      SECRET_KEY: ${SECRET_KEY}

      # OAuth 설정
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_KEY_ID: ${APPLE_KEY_ID}
      APPLE_PRIVATE_KEY: ${APPLE_PRIVATE_KEY}
      APPLE_SCHEME: ${APPLE_SCHEME}

      # Sendbird
      SENDBIRD_APP_ID: ${SENDBIRD_APP_ID}
      SENDBIRD_API_TOKEN: ${SENDBIRD_API_TOKEN}

      # Firebase
      FIREBASE_SERVICE_ACCOUNT_KEY: ${FIREBASE_SERVICE_ACCOUNT_KEY}

    volumes:
      - ./config/config.dev.yaml:/app/config/config.dev.yaml
      - ../shared:/app/shared
      - ../services/api/uploads:/app # dev 이미지 마운트
    ports:
      - "8002:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8002/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
